#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tests.UI.Views.Views.Projects
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    
    #line 2 "..\..\Views\Projects\New.cshtml"
    using System.Web.Mvc.Ajax;
    
    #line default
    #line hidden
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Projects\New.cshtml"
    using Common.Web.Mvc.Html;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.4.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Projects/New.cshtml")]
    public partial class New : System.Web.Mvc.WebViewPage<ScrumBoard.Domain.Project>
    {
        public New()
        {
        }
        public override void Execute()
        {
            
            #line 5 "..\..\Views\Projects\New.cshtml"
  
    ViewBag.Title = "New Project";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<hgroup");

WriteLiteral(" class=\"title\"");

WriteLiteral(">\r\n    <h1>");

            
            #line 10 "..\..\Views\Projects\New.cshtml"
   Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral(".</h1>\r\n    <h2>Create a new project.</h2>\r\n</hgroup>\r\n\r\n");

            
            #line 14 "..\..\Views\Projects\New.cshtml"
 using (Html.BeginForm()) {
    
            
            #line default
            #line hidden
            
            #line 15 "..\..\Views\Projects\New.cshtml"
Write(Html.ValidationSummary());

            
            #line default
            #line hidden
            
            #line 15 "..\..\Views\Projects\New.cshtml"
                             


            
            #line default
            #line hidden
WriteLiteral("    <fieldset>\r\n        <legend>Registration Form</legend>\r\n        <ol>\r\n       " +
"     <li>\r\n");

WriteLiteral("                ");

            
            #line 21 "..\..\Views\Projects\New.cshtml"
           Write(Html.LabelFor(m => m.Name, "Name"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 22 "..\..\Views\Projects\New.cshtml"
           Write(Html.DataBindedTextBoxFor(m => m.Name, new Dictionary<string, object> {{"valueUpdate", "'afterkeydown'"}}));

            
            #line default
            #line hidden
WriteLiteral(" \r\n            </li>\r\n            <li>\r\n");

WriteLiteral("                ");

            
            #line 25 "..\..\Views\Projects\New.cshtml"
           Write(Html.LabelFor(m => m.Vision, "Vision"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 26 "..\..\Views\Projects\New.cshtml"
           Write(Html.DataBindedTextAreaFor(m => m.Vision));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </li>\r\n            <li>\r\n");

WriteLiteral("                ");

            
            #line 29 "..\..\Views\Projects\New.cshtml"
           Write(Html.LabelFor(m => m.Name, "Code"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 30 "..\..\Views\Projects\New.cshtml"
           Write(Html.DataBindedTextBoxFor(m => m.Code));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </li>\r\n        </ol>\r\n        <input");

WriteLiteral(" id=\"submit\"");

WriteLiteral(" data-bind=\"click: create\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" value=\"Create\"");

WriteLiteral(" />\r\n    </fieldset>\r\n");

            
            #line 35 "..\..\Views\Projects\New.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n");

DefineSection("Scripts", () => {

WriteLiteral("\r\n\r\n");

WriteLiteral("    ");

            
            #line 39 "..\..\Views\Projects\New.cshtml"
Write(Scripts.Render("~/bundles/dynamicForms"));

            
            #line default
            #line hidden
WriteLiteral("    \r\n    \r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n        \r\n        $(document).ready(function () {\r\n\r\n            var viewModel" +
" = new ViewModels.Project.NewProjectViewModel({\r\n                apiPostUrl: \'/a" +
"pi/project\',\r\n                successRedirectUrl: \'");

            
            #line 47 "..\..\Views\Projects\New.cshtml"
                                Write(Url.Action("Dashboard", "Project", new { Area = "Project", projectKey = "[id]"}));

            
            #line default
            #line hidden
WriteLiteral("\'\r\n            });\r\n\r\n            viewModel.initialize();                       \r" +
"\n        });\r\n    </script>\r\n");

});

        }
    }
}
#pragma warning restore 1591
