#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tests.UI.Views.Views.Home
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.4.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/About.cshtml")]
    public partial class About : System.Web.Mvc.WebViewPage<dynamic>
    {
        public About()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Home\About.cshtml"
  
    ViewBag.Title = "About";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<hgroup");

WriteLiteral(" class=\"title\"");

WriteLiteral(">\r\n    <h1>");

            
            #line 6 "..\..\Views\Home\About.cshtml"
   Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral(@".</h1>
    <h2>Cause we love SCRUM and .Net</h2>
</hgroup>

<article>
    <p>
        We created this project because we weren't able to find a free and simple SCRUM administration application that suit our needs 
        and adopt SCRUM the way we see it.
    </p>
    <p>
        We also used this project as a validation platform for what we think are the best practices, architectural patterns, technologies 
        and disciplines that can be used to implement a system (at least a web application) using .Net framework.
    </p>
    <p>
        Our compromise is to leave ScrumBoard <strong>open source and free forever</strong>. As developers we want to contribute to the community by 
        providing a tool that we couldn’t find to use ourselves and also to get back to all the developers that publish their code, answer 
        questions in stack overflow, write blogs that enriches our knowledge and contribute with us in so many ways, so we hope that you 
        can benefit from this somehow to.
    </p>
    <p>
        We hope you enjoy using it as much as we enjoy working on it.
    </p>
</article>

<aside>
    <h3>Aside Title</h3>
    <p>
        Use this area to provide additional information.
    </p>
    <ul>
        <li>");

            
            #line 36 "..\..\Views\Home\About.cshtml"
       Write(Html.ActionLink("Home", "Index", "Home"));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n        <li>");

            
            #line 37 "..\..\Views\Home\About.cshtml"
       Write(Html.ActionLink("About", "About", "Home"));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n        <li>");

            
            #line 38 "..\..\Views\Home\About.cshtml"
       Write(Html.ActionLink("Contact", "Contact", "Home"));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n    </ul>\r\n</aside>");

        }
    }
}
#pragma warning restore 1591
