#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tests.UI.Views.Views.Home
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.4.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/Index.cshtml")]
    public partial class Index : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Index()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Home\Index.cshtml"
  
    ViewBag.Title = "Wellcome to ScrumBoard";

            
            #line default
            #line hidden
WriteLiteral("\r\n");

DefineSection("featured", () => {

WriteLiteral("\r\n    <section");

WriteLiteral(" class=\"featured\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"content-wrapper\"");

WriteLiteral(">\r\n            <hgroup");

WriteLiteral(" class=\"title\"");

WriteLiteral(">\r\n                <h1>");

            
            #line 8 "..\..\Views\Home\Index.cshtml"
               Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral(".</h1>\r\n                <h2>Cause we love SCRUM and .Net</h2>\r\n            </hgro" +
"up>\r\n            <p>Open source and free forever!</p>\r\n        </div>\r\n    </sec" +
"tion>\r\n");

});

WriteLiteral("<h3>Getting Started:</h3>\r\n<ol");

WriteLiteral(" class=\"round\"");

WriteLiteral(">\r\n    <li");

WriteLiteral(" class=\"one\"");

WriteLiteral(">\r\n        <h5>About</h5>\r\n        Read why we created this project int the about" +
" section.\r\n");

WriteLiteral("        ");

            
            #line 20 "..\..\Views\Home\Index.cshtml"
   Write(Html.ActionLink("Read more...", "About"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </li>\r\n\r\n    <li");

WriteLiteral(" class=\"two\"");

WriteLiteral(">\r\n        <h5>Go directly into action</h5>\r\n        Start working with ScrumBoar" +
"d by creating a new project and enjoy!\r\n");

WriteLiteral("        ");

            
            #line 26 "..\..\Views\Home\Index.cshtml"
   Write(Html.ActionLink("Create a new project", "New", "Projects"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </li>\r\n</ol>\r\n");

        }
    }
}
#pragma warning restore 1591
